<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23021" started-at="2018-03-15T11:39:36Z" finished-at="2018-03-15T11:39:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23021" started-at="2018-03-15T11:39:36Z" finished-at="2018-03-15T11:39:59Z">
      <class name="QGkuangjia.LoginTest">
        <test-method status="FAIL" signature="login2()[pri:0, instance:QGkuangjia.LoginTest@3bfdc050]" name="login2" duration-ms="22373" started-at="2018-03-15T11:39:36Z" finished-at="2018-03-15T11:39:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at QGkuangjia.LoginTest.login(LoginTest.java:19)
at QGkuangjia.LoginTest.login2(LoginTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login2 -->
        <test-method status="PASS" signature="login3()[pri:0, instance:QGkuangjia.LoginTest@3bfdc050]" name="login3" duration-ms="146" started-at="2018-03-15T11:39:59Z" finished-at="2018-03-15T11:39:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login3 -->
        <test-method status="PASS" signature="login4()[pri:0, instance:QGkuangjia.LoginTest@3bfdc050]" name="login4" duration-ms="173" started-at="2018-03-15T11:39:59Z" finished-at="2018-03-15T11:39:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login4 -->
        <test-method status="PASS" signature="login5()[pri:0, instance:QGkuangjia.LoginTest@3bfdc050]" name="login5" duration-ms="138" started-at="2018-03-15T11:39:59Z" finished-at="2018-03-15T11:39:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login5 -->
        <test-method status="PASS" signature="loginSuccess1()[pri:0, instance:QGkuangjia.LoginTest@3bfdc050]" name="loginSuccess1" duration-ms="114" started-at="2018-03-15T11:39:59Z" finished-at="2018-03-15T11:39:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSuccess1 -->
      </class> <!-- QGkuangjia.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
